### ISSUE TITLE
People links

### ISSUE THREAD

**Issue by dhilt** [developers-against-repressions/network-case#152]
Я добавил ссылку на себя в PR https://github.com/developers-against-repressions/network-case/pull/150 вида

```
[Денис Алексанов](https://github.com/dhilt)|Web Developer, SPb
```

Это окей? если нет, могу переоткрыть PR 

Но в принципе, я считаю, что ссылки на людей иметь было бы неплохо. Можно этот процесс автоматизировать, чтобы ссылки вставлялись автоматом при конвертировании из signed/ в README... что думаете?

**Comment by monich** [comment]
Прикольно, но кто будет по этим ссылкам ходить и зачем...

**Comment by fersel** [comment]
Привет, спасибо за участие!

Продублирую ответ из PR: мы думаем, что ставить ссылки самим на себя -- хорошо, но без автоматизации этого процесса для всех (в частности, поскольку этого могут не хотеть другие подписавшиеся).
